//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class ThumbnailMessage : Message
{
	public Sprite Thumbnail;

	public ThumbnailMessage (string title, string text, Sprite thumbnail) 
		: base(title, text)
	{
		Thumbnail = thumbnail;
	}

	new public void Display(MailboxController mailboxController)
	{
		base(mailboxController);
		mailboxController.Thumbnail.sprite = Thumbnail;
	}

}
