//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Assets.Scripts.Game;

public class Player
{
	public string _playerName;
	private int _playerId;

	public int Money;
	public Field CurrentField;

	public Player() {
		_playerId = GameLogic.Instance.GetNewPlayerId();
		_playerName = string.Format("Player {0}", _playerId);
		Money = 500;
	}

	public Player(string playerName) {
		_playerId = GameLogic.Instance.GetNewPlayerId();
		_playerName = playerName;
	}

	public override bool Equals(System.Object obj)
	{
		Player player = obj as Player;
		return _playerId == player.GetPlayerId();
	}

	public int GetPlayerId() 
	{
		return _playerId;
	}
}

