//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Assets.Scripts.Game;

public class TradeMessage : Message
{
	public Player PlayerA { get; private set; }
	public Player PlayerB { get; private set; }

	public ITradeable ItemA { get; private set; }
	public ITradeable ItemB { get; private set; }

	public TradeMessage (Player playerA, ITradeable itemA, Player playerB, ITradeable itemB)
		: base(null, "Trade request" )
	{
		PlayerA = playerA;
		PlayerB = playerB;

		ItemA = itemA;
		ItemB = itemB;
	}

	override public void Display(MessageDisplayController messageDisplayController)
	{
		base.Display(messageDisplayController);

		if(GameLogic.Instance.CurrentRound.GetCurrentPlayer() == PlayerA)
		{
			messageDisplayController.Text.text = "You want to trade with " + PlayerB.name;
		}
		else
		{
			messageDisplayController.Text.text = PlayerA.name + " wants to trade with you.";
			messageDisplayController.PositiveButton.gameObject.SetActive(true);
		}
		messageDisplayController.Thumbnail.sprite = ItemB.GetSprite();
	}

	override protected void NegativeAction()
	{
		PlayerA.Messages.Remove (this);
		PlayerB.Messages.Remove (this);
	}
	
	override protected void PositiveAction()
	{
		GameLogic.Instance.FinalizeTrade(PlayerA, ItemA, PlayerB, ItemB);

		NegativeAction();
	}

}
